# Generated by Django 4.2 on 2023-04-19 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
        migrations.AlterModelTable(
            name='reservation',
            table='reservation',
        ),
        migrations.AlterModelTable(
            name='room',
            table='room',
        ),
    ]
