# Generated by Django 4.2 on 2023-04-19 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0002_alter_client_table_alter_reservation_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='room_id',
            new_name='room',
        ),
    ]
