# Generated by Django 4.2 on 2023-04-19 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0003_rename_client_id_reservation_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Reservations.client'),
        ),
    ]
