# Generated by Django 4.2 on 2023-04-19 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0004_alter_reservation_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservations.client'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Reservations.room'),
        ),
    ]
