# Generated by Django 4.2 on 2023-04-19 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0005_alter_reservation_client_alter_reservation_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='client',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='room',
            new_name='room_id',
        ),
    ]
