# Generated by Django 4.2 on 2023-04-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0008_rename_client_reservation_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pay_method',
            field=models.CharField(choices=[('card', 'CARD'), ('cash', 'CASH'), ('other', 'OTHER')], max_length=5),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('paid', 'PAID'), ('removed', 'REMOVED')], max_length=7),
        ),
    ]
