# Generated by Django 4.2 on 2023-04-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0012_client_identification_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='identification_document',
            field=models.CharField(max_length=15),
        ),
    ]
