# Generated by Django 4.2 on 2023-04-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0013_alter_client_identification_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='stay_days',
            field=models.IntegerField(default=1),
        ),
    ]
