# Generated by Django 4.2 on 2023-04-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0014_alter_reservation_amount_alter_reservation_stay_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='amount',
            field=models.FloatField(default=1),
        ),
    ]
