# Generated by Django 4.2 on 2023-04-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0016_alter_reservation_amount_alter_reservation_stay_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='billing_info',
            field=models.CharField(max_length=100),
        ),
    ]
