# Generated by Django 4.2 on 2023-04-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0017_alter_reservation_billing_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=25, null=True),
        ),
    ]
